# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2025 Urias
"""
Database Management Package

This package provides all database functionality for SurfSifter,
including:

- Schema definitions (TableSchema, Column, FilterOp, etc.)
- Connection management and migrations (init_db, migrate, DatabaseManager)
- Generic CRUD helpers (insert_row, insert_rows, get_rows, delete_by_run)
- Domain-specific helpers (cookies, browser_history, images, etc.)
- Extractor statistics tracking

Usage:
    from core.database import (
        # Connection management
        init_db,
        migrate,
        DatabaseManager,

        # Schema types
        TableSchema,
        Column,
        FilterOp,
        FilterColumn,
        OrderColumn,
        ConflictAction,
        FilterSpec,
        TABLE_SCHEMAS,

        # Generic CRUD
        insert_row,
        insert_rows,
        get_rows,
        delete_by_run,
        get_distinct_values,
        get_count,

        # Domain-specific helpers (examples)
        insert_browser_history_row,
        get_browser_history,
        insert_cookie_row,
        get_cookies,

        # Statistics
        upsert_extractor_statistics,
        get_extractor_statistics_by_evidence,
        get_extractor_statistics_by_name,
    )

For backward compatibility, the old import paths still work:
    from core.database import init_db, migrate
    from core.database import TABLE_SCHEMAS, FilterOp
    from core.database import DatabaseManager
    from core.database import insert_row, insert_rows

Compatibility aliases are centralized in:
    from core.database import compat

Added domain-specific helper modules extracted from db.py.
"""

from __future__ import annotations

# Schema types and definitions
from .schema import (
    # Types from base.py
    ConflictAction,
    FilterOp,
    Column,
    FilterColumn,
    OrderColumn,
    TableSchema,
    FilterSpec,
    # All schema definitions from definitions.py
    TABLE_SCHEMAS,
)

# Individual schema definitions (for direct import compatibility)
from .schema.definitions import (
    URLS_SCHEMA,
    BROWSER_HISTORY_SCHEMA,
    IMAGES_SCHEMA,
    COOKIES_SCHEMA,
    BOOKMARKS_SCHEMA,
    BROWSER_DOWNLOADS_SCHEMA,
)

# Schema validation
from .schema.validator import (
    validate_schema,
    validate_all_schemas,
)

# Connection management
from .connection import (
    init_db,
    migrate,
)

# Database manager
from .manager import (
    DatabaseManager,
    slugify_label,
    ensure_case_structure,
    find_case_database,
    CASE_MIGRATIONS_DIR,
    EVIDENCE_MIGRATIONS_DIR,
    CASE_DB_SUFFIX,
    LEGACY_CASE_DB_SUFFIX,
    CASE_DB_GLOB,
    LEGACY_CASE_DB_GLOB,
)

# Generic CRUD helpers
from .helpers import (
    insert_row,
    insert_rows,
    get_rows,
    delete_by_run,
    get_distinct_values,
    get_count,
)

# Statistics helpers
from .helpers.statistics import (
    upsert_extractor_statistics,
    get_extractor_statistics_by_evidence,
    get_extractor_statistics_by_name,
    delete_extractor_statistics_by_evidence,
    delete_extractor_statistics_by_run,
    sync_process_log_from_statistics,
)

# Domain-specific helpers (all re-exported from helpers package)
from .helpers import (
    # Browser History
    insert_browser_history,
    insert_browser_history_row,
    insert_browser_history_rows,
    get_browser_history,
    get_browser_history_by_id,
    get_distinct_history_browsers,
    get_distinct_history_profiles,
    get_browser_history_stats,
    delete_browser_history_by_run,
    # Cookies
    insert_cookie_row,
    insert_cookies,
    get_cookies,
    get_cookie_domains,
    get_cookie_by_id,
    get_distinct_cookie_browsers,
    delete_cookies_by_run,
    # Bookmarks
    insert_bookmark_row,
    insert_bookmarks,
    get_bookmarks,
    get_bookmark_folders,
    delete_bookmarks_by_run,
    get_distinct_bookmark_browsers,
    # Browser Downloads
    insert_browser_download_row,
    insert_browser_downloads,
    get_browser_downloads,
    get_browser_download_stats,
    delete_browser_downloads_by_run,
    get_distinct_download_browsers,
    # Investigator Downloads
    insert_download,
    update_download_status,
    update_download_image_metadata,
    get_download,
    get_download_by_path,
    get_downloads,
    get_download_count,
    get_download_stats,
    get_download_domains,
    get_url_download_status,
    find_url_by_filename_domain,
    # Download Audit
    insert_download_audit,
    get_download_audit,
    get_download_audit_count,
    get_download_audit_summary,
    # Images
    insert_image,
    insert_images,
    get_images,
    get_image_by_id,
    get_image_by_md5,
    get_image_by_sha256,
    get_image_stats,
    delete_images_by_run,
    update_image_tags,
    update_image_notes,
    insert_image_discovery,
    get_image_discoveries,
    insert_image_with_discovery,
    get_image_sources,
    get_image_fs_path,
    delete_discoveries_by_run,
    # URLs
    insert_url_row,
    insert_urls,
    get_urls,
    get_url_by_id,
    get_url_stats,
    delete_urls_by_run,
    insert_url_groups,
    get_url_groups,
    # URL Tags
    insert_url_tags,
    get_url_tags,
    # Timeline
    insert_timeline_event,
    insert_timeline_events,
    get_timeline_events,
    get_timeline_stats,
    delete_timeline_by_run,
    clear_timeline,
    iter_timeline,
    get_timeline_kinds,
    get_timeline_confidences,
    # Process Log
    insert_process_log,
    get_process_logs,
    create_process_log,
    finalize_process_log,
    # Artifacts (bulk_extractor)
    insert_bitcoins,
    get_bitcoins,
    delete_bitcoins_by_run,
    insert_ethereums,
    get_ethereums,
    delete_ethereums_by_run,
    insert_emails,
    get_emails,
    delete_emails_by_run,
    insert_domains,
    get_domains,
    delete_domains_by_run,
    insert_ips,
    get_ips,
    delete_ips_by_run,
    insert_phones,
    get_phones,
    delete_phones_by_run,
    # Autofill
    insert_autofill_entry,
    insert_autofill_entries,
    get_autofill_entries,
    delete_autofill_by_run,
    insert_autofill_profile,
    insert_autofill_profiles,
    get_autofill_profiles,
    delete_autofill_profiles_by_run,
    insert_credential,
    insert_credentials,
    get_credentials,
    delete_credentials_by_run,
    insert_credit_card,
    insert_credit_cards,
    get_credit_cards,
    delete_credit_cards_by_run,
    # Autofill IBANs (Chromium/Edge)
    insert_autofill_iban,
    insert_autofill_ibans,
    get_autofill_ibans,
    get_distinct_autofill_iban_browsers,
    delete_autofill_ibans_by_run,
    # Autofill Profile Tokens (Chromium 100+)
    CHROMIUM_TOKEN_TYPES,
    get_token_type_name,
    insert_autofill_profile_token,
    insert_autofill_profile_tokens,
    get_autofill_profile_tokens,
    delete_autofill_profile_tokens_by_run,
    # Deleted Form History (Firefox)
    insert_deleted_form_history,
    insert_deleted_form_history_entries,
    get_deleted_form_history,
    get_distinct_deleted_form_history_browsers,
    delete_deleted_form_history_by_run,
    # Search Engines
    insert_search_engine,
    insert_search_engines,
    get_search_engines,
    delete_search_engines_by_run,
    # Sessions
    insert_session_window,
    insert_session_windows,
    get_session_windows,
    get_session_window_by_id,
    delete_session_windows_by_run,
    insert_session_tab,
    insert_session_tabs,
    get_session_tabs,
    delete_session_tabs_by_run,
    insert_session_tab_history,
    insert_session_tab_histories,
    get_session_tab_history,
    delete_session_tab_history_by_run,
    insert_closed_tab,
    insert_closed_tabs,
    get_closed_tabs,
    delete_closed_tabs_by_run,
    insert_session_form_data,
    insert_session_form_datas,
    get_session_form_data,
    delete_session_form_data_by_run,
    delete_sessions_by_run,
    # Permissions
    insert_permission,
    insert_permissions,
    get_permissions,
    get_distinct_permission_types,
    delete_permissions_by_run,
    # Media
    insert_media_playback,
    insert_media_playbacks,
    get_media_playback,
    delete_media_playback_by_run,
    insert_media_session,
    insert_media_sessions,
    get_media_sessions,
    delete_media_sessions_by_run,
    # Media origins
    insert_media_origin,
    insert_media_origins,
    get_media_origins,
    delete_media_origins_by_run,
    # Media stats
    get_media_stats,
    delete_media_by_run,
    # HSTS
    insert_hsts_entry,
    insert_hsts_entries,
    get_hsts_entries,
    get_hsts_stats,
    delete_hsts_by_run,
    # Jump Lists
    insert_jump_list_entry,
    insert_jump_list_entries,
    get_jump_list_entries,
    get_jump_list_stats,
    delete_jump_list_by_run,
    # Extensions
    insert_extension,
    insert_extensions,
    get_extensions,
    get_extension_stats,
    delete_extensions_by_run,
    # Storage
    insert_local_storage,
    insert_local_storages,
    get_local_storage,
    get_local_storage_origins,
    delete_local_storage_by_run,
    insert_session_storage,
    insert_session_storages,
    get_session_storage,
    delete_session_storage_by_run,
    insert_indexeddb_database,
    insert_indexeddb_databases,
    get_indexeddb_databases,
    delete_indexeddb_databases_by_run,
    insert_indexeddb_entry,
    insert_indexeddb_entries,
    get_indexeddb_entries,
    delete_indexeddb_entries_by_run,
    insert_storage_token,
    insert_storage_tokens,
    get_storage_tokens,
    get_storage_token_stats,
    delete_storage_tokens_by_run,
    insert_storage_identifier,
    insert_storage_identifiers,
    get_storage_identifiers,
    get_storage_identifier_stats,
    delete_storage_identifiers_by_run,
    get_stored_sites_summary,
    # Site Engagement
    insert_site_engagement,
    insert_site_engagements,
    get_site_engagements,
    get_site_engagement_stats,
    delete_site_engagement_by_run,
    delete_site_engagement_by_evidence,
    get_top_engaged_sites,
    # Stored Sites (materialized view for tagging)
    insert_stored_site,
    upsert_stored_site,
    get_stored_sites,
    get_stored_site_by_id,
    get_stored_site_by_origin,
    refresh_stored_sites,
    delete_stored_sites_by_evidence,
    get_stored_sites_for_report,
    # Sync Data
    insert_sync_data,
    insert_sync_datas,
    insert_sync_data_row,
    get_sync_data,
    delete_sync_data_by_run,
    insert_synced_device,
    insert_synced_devices,
    insert_synced_device_row,
    get_synced_devices,
    delete_synced_devices_by_run,
    get_sync_stats,
    # Favicons
    insert_favicon,
    insert_favicons,
    get_favicons,
    get_favicon_by_hash,
    get_favicon_by_id,
    delete_favicons_by_run,
    insert_favicon_mapping,
    insert_favicon_mappings,
    get_favicon_mappings,
    delete_favicon_mappings_by_run,
    insert_top_site,
    insert_top_sites,
    get_top_sites,
    get_top_sites_stats,
    delete_top_sites_by_run,
    get_favicon_stats,
    # Browser Inventory
    insert_browser_inventory,
    update_inventory_ingestion_status,
    get_browser_inventory,
    # Batch Operations
    get_evidence_table_counts,
    purge_evidence_data,
    PURGEABLE_TABLES,
    # OS Indicators
    insert_os_indicator,
    insert_os_indicators,
    get_os_indicators,
    delete_os_indicators_by_run,
    insert_platform_detection,
    insert_platform_detections,
    get_platform_detections,
    delete_platform_detections_by_run,
    # Hash Matches
    insert_hash_match,
    insert_hash_matches,
    get_hash_matches,
    delete_hash_matches_by_run,
    insert_url_match,
    insert_url_matches,
    get_url_matches,
    delete_url_matches_by_run,
    # Extracted Files
    insert_extracted_file,
    insert_extracted_files,
    insert_extracted_files_batch,
    get_extracted_files,
    get_extracted_file_by_id,
    get_extracted_file_by_sha256,
    get_extraction_stats,
    get_distinct_extractors,
    get_distinct_run_ids,
    delete_extracted_files_by_run,
    delete_extracted_files_by_extractor,
    # Extraction Warnings
    WARNING_TYPE_UNKNOWN_TABLE,
    WARNING_TYPE_UNKNOWN_COLUMN,
    WARNING_TYPE_UNKNOWN_TOKEN_TYPE,
    WARNING_TYPE_JSON_PARSE_ERROR,
    CATEGORY_DATABASE,
    CATEGORY_JSON,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    SEVERITY_ERROR,
    insert_extraction_warning,
    insert_extraction_warnings,
    get_extraction_warnings,
    get_extraction_warnings_summary,
    delete_extraction_warnings_by_run,
    delete_extraction_warnings_by_extractor,
    get_warning_count_for_extractor,
    # Firefox Cache Index
    insert_firefox_cache_index_entry,
    insert_firefox_cache_index_entries,
    get_firefox_cache_index_entries,
    get_firefox_cache_index_stats,
    delete_firefox_cache_index_by_run,
)

# Internal function for upgrade path tests (exposed for test compatibility)
from .manager import _ensure_file_list_partition_columns

# -------------------------------------------------------------------------
# Compatibility aliases for backward compatibility
# Centralized in core.database.compat (public compatibility boundary).
# -------------------------------------------------------------------------
from . import compat
from .compat import (
    insert_bitcoin_addresses,
    get_bitcoin_addresses,
    insert_ethereum_addresses,
    get_ethereum_addresses,
    insert_ip_addresses,
    get_ip_addresses,
    insert_telephone_numbers,
    get_telephone_numbers,
    insert_autofill,
    get_autofill,
    insert_site_permissions,
    get_site_permissions,
    delete_jump_lists_by_run,
    insert_browser_extension_row,
    insert_browser_extensions,
    get_browser_extensions,
    get_browser_extension_stats,
    delete_browser_extensions_by_run,
    insert_local_storage_row,
    insert_local_storage_rows,
    insert_session_storage_row,
    insert_session_storage_rows,
    insert_indexeddb_database_row,
    insert_indexeddb_entry_row,
    delete_indexeddb_by_run,
)

__all__ = [
    # Schema types
    "ConflictAction",
    "FilterOp",
    "Column",
    "FilterColumn",
    "OrderColumn",
    "TableSchema",
    "FilterSpec",
    "TABLE_SCHEMAS",
    # Individual schemas (for direct import)
    "URLS_SCHEMA",
    "BROWSER_HISTORY_SCHEMA",
    "IMAGES_SCHEMA",
    "COOKIES_SCHEMA",
    "BOOKMARKS_SCHEMA",
    "BROWSER_DOWNLOADS_SCHEMA",
    # Validation
    "validate_schema",
    "validate_all_schemas",
    # Connection
    "init_db",
    "migrate",
    # Manager
    "DatabaseManager",
    "slugify_label",
    "ensure_case_structure",
    "find_case_database",
    "CASE_MIGRATIONS_DIR",
    "EVIDENCE_MIGRATIONS_DIR",
    "CASE_DB_SUFFIX",
    "LEGACY_CASE_DB_SUFFIX",
    "CASE_DB_GLOB",
    "LEGACY_CASE_DB_GLOB",
    # Generic CRUD helpers
    "insert_row",
    "insert_rows",
    "get_rows",
    "delete_by_run",
    "get_distinct_values",
    "get_count",
    # Statistics
    "upsert_extractor_statistics",
    "get_extractor_statistics_by_evidence",
    "get_extractor_statistics_by_name",
    "delete_extractor_statistics_by_evidence",
    "delete_extractor_statistics_by_run",
    "sync_process_log_from_statistics",
    # Browser History
    "insert_browser_history",
    "insert_browser_history_row",
    "insert_browser_history_rows",
    "get_browser_history",
    "get_browser_history_by_id",
    "get_distinct_history_browsers",
    "get_distinct_history_profiles",
    "get_browser_history_stats",
    "delete_browser_history_by_run",
    # Cookies
    "insert_cookie_row",
    "insert_cookies",
    "get_cookies",
    "get_cookie_domains",
    "get_cookie_by_id",
    "get_distinct_cookie_browsers",
    "delete_cookies_by_run",
    # Bookmarks
    "insert_bookmark_row",
    "insert_bookmarks",
    "get_bookmarks",
    "get_bookmark_folders",
    "delete_bookmarks_by_run",
    "get_distinct_bookmark_browsers",
    # Browser Downloads
    "insert_browser_download_row",
    "insert_browser_downloads",
    "get_browser_downloads",
    "get_browser_download_stats",
    "delete_browser_downloads_by_run",
    "get_distinct_download_browsers",
    # Investigator Downloads
    "insert_download",
    "update_download_status",
    "update_download_image_metadata",
    "get_download",
    "get_download_by_path",
    "get_downloads",
    "get_download_count",
    "get_download_stats",
    "get_download_domains",
    "get_url_download_status",
    "find_url_by_filename_domain",
    # Download Audit
    "insert_download_audit",
    "get_download_audit",
    "get_download_audit_count",
    "get_download_audit_summary",
    # Images
    "insert_image",
    "insert_images",
    "get_images",
    "get_image_by_id",
    "get_image_by_md5",
    "get_image_by_sha256",
    "get_image_stats",
    "delete_images_by_run",
    "update_image_tags",
    "update_image_notes",
    "insert_image_discovery",
    "get_image_discoveries",
    "insert_image_with_discovery",
    "get_image_sources",
    "get_image_fs_path",
    "delete_discoveries_by_run",
    # URLs
    "insert_url_row",
    "insert_urls",
    "get_urls",
    "get_url_by_id",
    "get_url_stats",
    "delete_urls_by_run",
    "insert_url_groups",
    "get_url_groups",
    # URL Tags
    "insert_url_tags",
    "get_url_tags",
    # Timeline
    "insert_timeline_event",
    "insert_timeline_events",
    "get_timeline_events",
    "get_timeline_stats",
    "delete_timeline_by_run",
    "clear_timeline",
    "iter_timeline",
    "get_timeline_kinds",
    "get_timeline_confidences",
    # Process Log
    "insert_process_log",
    "get_process_logs",
    "create_process_log",
    "finalize_process_log",
    # Artifacts (bulk_extractor)
    "insert_bitcoins",
    "insert_bitcoin_addresses",
    "get_bitcoins",
    "get_bitcoin_addresses",
    "delete_bitcoins_by_run",
    "insert_ethereums",
    "insert_ethereum_addresses",
    "get_ethereums",
    "get_ethereum_addresses",
    "delete_ethereums_by_run",
    "insert_emails",
    "get_emails",
    "delete_emails_by_run",
    "insert_domains",
    "get_domains",
    "delete_domains_by_run",
    "insert_ips",
    "insert_ip_addresses",
    "get_ips",
    "get_ip_addresses",
    "delete_ips_by_run",
    "insert_phones",
    "insert_telephone_numbers",
    "get_phones",
    "get_telephone_numbers",
    "delete_phones_by_run",
    # Autofill
    "insert_autofill_entry",
    "insert_autofill_entries",
    "insert_autofill",
    "get_autofill_entries",
    "get_autofill",
    "delete_autofill_by_run",
    "insert_autofill_profile",
    "insert_autofill_profiles",
    "get_autofill_profiles",
    "delete_autofill_profiles_by_run",
    "insert_credential",
    "insert_credentials",
    "get_credentials",
    "delete_credentials_by_run",
    "insert_credit_card",
    "insert_credit_cards",
    "get_credit_cards",
    "delete_credit_cards_by_run",
    # Autofill IBANs (Chromium/Edge)
    "insert_autofill_iban",
    "insert_autofill_ibans",
    "get_autofill_ibans",
    "get_distinct_autofill_iban_browsers",
    "delete_autofill_ibans_by_run",
    # Autofill Profile Tokens (Chromium 100+)
    "CHROMIUM_TOKEN_TYPES",
    "get_token_type_name",
    "insert_autofill_profile_token",
    "insert_autofill_profile_tokens",
    "get_autofill_profile_tokens",
    "delete_autofill_profile_tokens_by_run",
    # Deleted Form History (Firefox)
    "insert_deleted_form_history",
    "insert_deleted_form_history_entries",
    "get_deleted_form_history",
    "get_distinct_deleted_form_history_browsers",
    "delete_deleted_form_history_by_run",
    # Search Engines
    "insert_search_engine",
    "insert_search_engines",
    "get_search_engines",
    "delete_search_engines_by_run",
    # Sessions
    "insert_session_window",
    "insert_session_windows",
    "get_session_windows",
    "get_session_window_by_id",
    "delete_session_windows_by_run",
    "insert_session_tab",
    "insert_session_tabs",
    "get_session_tabs",
    "delete_session_tabs_by_run",
    "insert_session_tab_history",
    "insert_session_tab_histories",
    "get_session_tab_history",
    "delete_session_tab_history_by_run",
    "insert_closed_tab",
    "insert_closed_tabs",
    "get_closed_tabs",
    "delete_closed_tabs_by_run",
    "insert_session_form_data",
    "insert_session_form_datas",
    "get_session_form_data",
    "delete_session_form_data_by_run",
    "delete_sessions_by_run",
    # Permissions
    "insert_permission",
    "insert_permissions",
    "insert_site_permissions",
    "get_permissions",
    "get_site_permissions",
    "get_distinct_permission_types",
    "delete_permissions_by_run",
    # Media
    "insert_media_playback",
    "insert_media_playbacks",
    "get_media_playback",
    "delete_media_playback_by_run",
    "insert_media_session",
    "insert_media_sessions",
    "get_media_sessions",
    "delete_media_sessions_by_run",
    # Media origins
    "insert_media_origin",
    "insert_media_origins",
    "get_media_origins",
    "delete_media_origins_by_run",
    # Media stats
    "get_media_stats",
    "delete_media_by_run",
    # HSTS
    "insert_hsts_entry",
    "insert_hsts_entries",
    "get_hsts_entries",
    "get_hsts_stats",
    "delete_hsts_by_run",
    # Jump Lists
    "insert_jump_list_entry",
    "insert_jump_list_entries",
    "get_jump_list_entries",
    "get_jump_list_stats",
    "delete_jump_list_by_run",
    "delete_jump_lists_by_run",
    # Extensions
    "insert_extension",
    "insert_extensions",
    "insert_browser_extension_row",
    "insert_browser_extensions",
    "get_extensions",
    "get_browser_extensions",
    "get_extension_stats",
    "get_browser_extension_stats",
    "delete_extensions_by_run",
    "delete_browser_extensions_by_run",
    # Storage
    "insert_local_storage",
    "insert_local_storages",
    "get_local_storage",
    "get_local_storage_origins",
    "delete_local_storage_by_run",
    "insert_session_storage",
    "insert_session_storages",
    "get_session_storage",
    "delete_session_storage_by_run",
    "insert_indexeddb_database",
    "insert_indexeddb_databases",
    "get_indexeddb_databases",
    "delete_indexeddb_databases_by_run",
    "insert_indexeddb_entry",
    "insert_indexeddb_entries",
    "get_indexeddb_entries",
    "delete_indexeddb_entries_by_run",
    "insert_storage_token",
    "insert_storage_tokens",
    "get_storage_tokens",
    "get_storage_token_stats",
    "delete_storage_tokens_by_run",
    "insert_storage_identifier",
    "insert_storage_identifiers",
    "get_storage_identifiers",
    "get_storage_identifier_stats",
    "delete_storage_identifiers_by_run",
    "get_stored_sites_summary",
    # Site Engagement
    "insert_site_engagement",
    "insert_site_engagements",
    "get_site_engagements",
    "get_site_engagement_stats",
    "delete_site_engagement_by_run",
    "delete_site_engagement_by_evidence",
    "get_top_engaged_sites",
    # Stored Sites (materialized view for tagging)
    "insert_stored_site",
    "upsert_stored_site",
    "get_stored_sites",
    "get_stored_site_by_id",
    "get_stored_site_by_origin",
    "refresh_stored_sites",
    "delete_stored_sites_by_evidence",
    "get_stored_sites_for_report",
    # Sync Data
    "insert_sync_data",
    "insert_sync_datas",
    "insert_sync_data_row",
    "get_sync_data",
    "delete_sync_data_by_run",
    "insert_synced_device",
    "insert_synced_devices",
    "insert_synced_device_row",
    "get_synced_devices",
    "delete_synced_devices_by_run",
    "get_sync_stats",
    # Favicons
    "insert_favicon",
    "insert_favicons",
    "get_favicons",
    "get_favicon_by_hash",
    "get_favicon_by_id",
    "delete_favicons_by_run",
    "insert_favicon_mapping",
    "insert_favicon_mappings",
    "get_favicon_mappings",
    "delete_favicon_mappings_by_run",
    "insert_top_site",
    "insert_top_sites",
    "get_top_sites",
    "get_top_sites_stats",
    "delete_top_sites_by_run",
    "get_favicon_stats",
    # Browser Inventory
    "insert_browser_inventory",
    "update_inventory_ingestion_status",
    "get_browser_inventory",
    # Batch Operations
    "get_evidence_table_counts",
    "purge_evidence_data",
    "PURGEABLE_TABLES",
    # OS Indicators
    "insert_os_indicator",
    "insert_os_indicators",
    "get_os_indicators",
    "delete_os_indicators_by_run",
    "insert_platform_detection",
    "insert_platform_detections",
    "get_platform_detections",
    "delete_platform_detections_by_run",
    # Hash Matches
    "insert_hash_match",
    "insert_hash_matches",
    "get_hash_matches",
    "delete_hash_matches_by_run",
    "insert_url_match",
    "insert_url_matches",
    "get_url_matches",
    "delete_url_matches_by_run",
    # Internal (for tests)
    "_ensure_file_list_partition_columns",
    # Compatibility boundary module
    "compat",
    # Legacy aliases for backward compatibility
    "insert_local_storage_row",
    "insert_local_storage_rows",
    "insert_session_storage_row",
    "insert_session_storage_rows",
    "insert_indexeddb_database_row",
    "insert_indexeddb_entry_row",
    "delete_indexeddb_by_run",
    # Extraction Warnings
    "WARNING_TYPE_UNKNOWN_TABLE",
    "WARNING_TYPE_UNKNOWN_COLUMN",
    "WARNING_TYPE_UNKNOWN_TOKEN_TYPE",
    "WARNING_TYPE_JSON_PARSE_ERROR",
    "CATEGORY_DATABASE",
    "CATEGORY_JSON",
    "SEVERITY_INFO",
    "SEVERITY_WARNING",
    "SEVERITY_ERROR",
    "insert_extraction_warning",
    "insert_extraction_warnings",
    "get_extraction_warnings",
    "get_extraction_warnings_summary",
    "delete_extraction_warnings_by_run",
    "delete_extraction_warnings_by_extractor",
    "get_warning_count_for_extractor",
    # Firefox Cache Index
    "insert_firefox_cache_index_entry",
    "insert_firefox_cache_index_entries",
    "get_firefox_cache_index_entries",
    "get_firefox_cache_index_stats",
    "delete_firefox_cache_index_by_run",
]
